<a href="https://colab.research.google.com/github/samuelbolugee/PythonDSProjects/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

To use NumPy in your Python code, you need to import it at the beginning of your script. Conventionally, NumPy is imported under the alias "np":

In [ ]:
import numpy as np


The fundamental object in NumPy is the ndarray (n-dimensional array). NumPy arrays are similar to Python lists, but they offer more efficient storage and faster computations for numerical operations. Here's how you can create a NumPy array:

In [ ]:
# Create a 1-dimensional array from a Python list
arr1d = np.array([1, 2, 3, 4, 5])

# Create a 2-dimensional array from a nested list
arr2d = np.array([[1, 2, 3], [4, 5, 6]])

# Create a 3-dimensional array using NumPy functions
arr3d = np.zeros((2, 3, 4))  # Creates a 2x3x4 array of zeros
arr3d = np.random.rand(2, 3, 4)  # Creates a 2x3x4 array with random values between 0 and 1


NumPy arrays have several useful attributes and methods. Here are a few commonly used ones:

In [ ]:
# Shape: Returns the dimensions of the array
print(arr2d.shape)  # Output: (2, 3) - 2 rows, 3 columns

# Size: Returns the total number of elements in the array
print(arr2d.size)  # Output: 6

# dtype: Returns the data type of the elements in the array
print(arr2d.dtype)  # Output: int64

# Reshape: Changes the shape of the array
reshaped_arr = arr2d.reshape(2, 3)  # Reshapes arr1d into a 2x3 array

# Slicing: Extracts a portion of the array
slice_arr = arr1d[2:5]  # Returns elements from index 2 to 4 (exclusive)


(2, 3)
6
int64


NumPy provides a wide range of mathematical functions and operations that can be performed on arrays. Here are a few examples:

In [ ]:
# Element-wise operations
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Addition
result = a + b  # Output: [5, 7, 9]

# Multiplication
result = a * b  # Output: [4, 10, 18]

# Matrix multiplication
result = np.dot(a, b)  # Output: 32

# Mathematical functions
arr = np.array([1, 2, 3])

# Square root
result = np.sqrt(arr)  # Output: [1.0, 1.41421356, 1.73205081]

# Exponential
result = np.exp(arr)  # Output: [2.71828183, 7.3890561, 20.08553692]


Broadcasting is a powerful feature in NumPy that allows arrays with different shapes to be used in arithmetic operations. It eliminates the need for explicit looping and improves code readability. Here's an example:

In [ ]:
# Broadcasting example
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([10, 20, 30])

# Add 'b' to each row of 'a' using broadcasting
result = a + b
print(result)
# Output:
# [[11 22 33]
#  [14 25 36]]


[[11 22 33]
 [14 25 36]]


NumPy provides various functions to manipulate arrays, such as reshaping, joining, splitting, and more. Here are a few examples:

In [ ]:
# Reshaping arrays
arr = np.array([1, 2, 3, 4, 5, 6])
reshaped = arr.reshape(2, 3)
print(reshaped)
# Output:
# [[1 2 3]
#  [4 5 6]]

# Joining arrays
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
result = np.concatenate((a, b))
print(result)
# Output: [1 2 3 4 5 6]

# Splitting arrays
arr = np.array([1, 2, 3, 4, 5, 6])
result = np.split(arr, 3)
print(result)
# Output: [array([1, 2]), array([3, 4]), array([5, 6])]


[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]
[array([1, 2]), array([3, 4]), array([5, 6])]


NumPy provides universal functions (ufuncs) that operate element-wise on arrays and support various mathematical operations. Some common ufuncs include np.sin(), np.cos(), np.exp(), np.log(), and more. Here's an example:

In [ ]:
arr = np.array([0, np.pi/2, np.pi])
result = np.sin(arr)
print(result)
# Output: [0.         1.         1.2246468e-16]


[0.0000000e+00 1.0000000e+00 1.2246468e-16]


NumPy supports advanced indexing techniques, such as integer array indexing and Boolean array indexing. These techniques enable advanced selection and manipulation of array elements. Here are a few examples:

In [ ]:
arr = np.array([[1, 2], [3, 4], [5, 6]])

# Integer array indexing
result = arr[[0, 2], [1, 0]]
print(result)
# Output: [2 5]

# Boolean array indexing
mask = arr > 2
result = arr[mask]
print(result)
# Output: [3 4 5 6]


[2 5]
[3 4 5 6]


NumPy provides a comprehensive set of linear algebra functions for matrix operations. You can perform operations like matrix multiplication, inverse, determinant, eigenvalues, and more. Here's an example:

In [ ]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

# Matrix multiplication
result = np.matmul(a, b)
print(result)
# Output:
# [[19 22]
#  [43 50]]

# Matrix determinant
result = np.linalg.det(a)
print(result)
# Output: -2.0

# Matrix inverse
result = np.linalg.inv(a)
print(result)
# Output:
# [[-2.   1. ]
#  [ 1.5 -0.5]]


[[19 22]
 [43 50]]
-2.0000000000000004
[[-2.   1. ]
 [ 1.5 -0.5]]


Fancy indexing allows you to use arrays of indices to access or manipulate elements of an array. Here's an example:

In [ ]:
arr = np.array([10, 20, 30, 40, 50])
indices = np.array([1, 3])

# Access elements at specified indices
result = arr[indices]
print(result)
# Output: [20 40]

# Modify elements at specified indices
arr[indices] = 99
print(arr)
# Output: [10 99 30 99 50]


[20 40]
[10 99 30 99 50]


Vectorization is a technique that performs operations on entire arrays rather than individual elements. It improves performance and readability of the code. Here's an example:

In [ ]:
# Calculate the Euclidean distance between two arrays
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Vectorized calculation
distance = np.sqrt(np.sum((a - b) ** 2))
print(distance)
# Output: 5.196152422706632


5.196152422706632


Structured arrays allow you to define custom data types and organize data with different types into a single array. Here's an example:

In [ ]:
# Define a structured data type
dt = np.dtype([('name', 'S10'), ('age', int), ('height', float)])

# Create a structured array
arr = np.array([('John', 30, 175.2), ('Alice', 25, 162.5)], dtype=dt)

# Accessing elements by field name
print(arr['name'])
# Output: [b'John' b'Alice']

# Accessing elements by row and field name
print(arr[1]['age'])
# Output: 25


[b'John' b'Alice']
25


You can use Boolean masks to apply conditions and perform operations on arrays with different shapes.

In [ ]:
# Broadcasting with masks
arr = np.array([1, 2, 3, 4, 5])
mask = np.array([True, False, True, False, False])

# Multiply elements that satisfy the condition by 2
result = arr[mask] * 2
print(result)
# Output: [2 6]


[2 6]


NumPy integrates well with the pandas library, which is widely used for data manipulation and analysis. You can convert NumPy arrays to pandas DataFrames for more advanced data processing.

In [ ]:
import pandas as pd

# Convert NumPy array to DataFrame
data = np.array([[1, 2, 3], [4, 5, 6]])
df = pd.DataFrame(data, columns=['A', 'B', 'C'])

# Perform operations on DataFrame
df['D'] = df['A'] + df['B']
print(df)
# Output:
#    A  B  C  D
# 0  1  2  3  3
# 1  4  5  6  9


   A  B  C  D
0  1  2  3  3
1  4  5  6  9
